---

- hosts: all
  become: true
  tasks:
  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"




- hosts: web_servers
  become: true
  tasks: 
  - name: install apache2 package and php support for ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name: 
         - apache2
         - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

